version: '2.4'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=staging
      - POSTGRES_PASSWORD=staging
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seeds.sql:/docker-entrypoint-initdb.d/2-seeds.sql
    ports:
      - 7232:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgraphile:
    build:
      context: ./postgraphile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5433:5433
    command:
      - --connection
      - postgres://staging:staging@postgres:5432/staging
      - --port
      - "5433"
      - --schema
      - app
    labels:
      - traefik.http.routers.postgraphile.rule=Host(`localhost`) && PathPrefix(`/graphql`)
      - traefik.http.services.postgraphile.loadbalancer.server.port=5433

  frontend:
    build:
      context: ./frontend
    labels:
      - traefik.http.routers.frontend.rule=Host(`localhost`)

  router:
    image: traefik:v2.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker
    ports:
      - 80:80
