name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
        working-directory: ./frontend
      - run: yarn lint
        working-directory: ./frontend
